# Enable for k8s version 1.23+
#apiVersion: autoscaling/v2
#kind: HorizontalPodAutoscaler
#metadata:
#  name: apollo
#spec:
#  scaleTargetRef:
#    apiVersion: apps/v1
#    kind: Deployment
#    name: apollo
#  minReplicas: 3
#  maxReplicas: 5
#  metrics:
#  - type: Resource
#    resource:
#      name: cpu
#      target:
#        type: Utilization
#        averageUtilization: 50

apiVersion: autoscaling/v1
kind: HorizontalPodAutoscaler
metadata:
  name: apollo
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: apollo
  minReplicas: 3
  maxReplicas: 6
  targetCPUUtilizationPercentage: 50