---

apiVersion: apps/v1
kind: Deployment

metadata:
  name: apollo
  labels:
    comp: apollo

spec:
  replicas: 3
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      comp: apollo
  template:
    metadata:
      annotations: {}
      labels:
        comp: apollo
    spec:
      containers:
      - name: apollo
        image: opsani/co-http:latest
        args: [ 'busy=10' ]
        resources:
          limits:
            cpu: 1000m
            memory: 1Gi
          requests:
            cpu: 1000m
            memory: 1Gi
        ports:
          - containerPort: 8080

---

apiVersion: v1
kind: Service

metadata:
  name: apollo

spec:
  selector:
    comp: apollo
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080