---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: apollo
  labels:
    app: apollo
    app.kubernetes.io/name: apollo
    app.kubernetes.io/component: apollo

spec:
  replicas: 3
  serviceName: apollo
  revisionHistoryLimit: 2
  selector:
    matchLabels:
      app: apollo
      app.kubernetes.io/name: apollo
      app.kubernetes.io/component: apollo
  template:
    metadata:
      annotations: {}
      labels:
        app: apollo
        app.kubernetes.io/name: apollo
        app.kubernetes.io/component: apollo
    spec:
      terminationGracePeriodSeconds: 10
      containers:
      - name: apollo
        image: opsani/co-http:latest
        args: [ 'busy=10' ]
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
          requests:
            cpu: 500m
            memory: 1Gi
        ports:
          - containerPort: 8080

---

apiVersion: v1
kind: Service

metadata:
  name: apollo

spec:
  selector:
    app: apollo
    app.kubernetes.io/name: apollo
    app.kubernetes.io/component: apollo
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
